// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: rpcmeta.proto
// Protobuf Java Version: 4.32.0

package com.qifly.core.protocol.frame.meta;

@com.google.protobuf.Generated
public final class RpcMeta {
  private RpcMeta() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 32,
      /* patch= */ 0,
      /* suffix= */ "",
      RpcMeta.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_RpcMetaData_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_RpcMetaData_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Trace_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Trace_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rrpcmeta.proto\"$\n\013RpcMetaData\022\025\n\005trace\030" +
      "\001 \001(\0132\006.Trace\"*\n\005Trace\022\020\n\010trace_id\030\001 \001(\t" +
      "\022\017\n\007span_id\030\002 \001(\tB2\n\"com.qifly.core.prot" +
      "ocol.frame.metaB\007RpcMetaP\001\210\001\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_RpcMetaData_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_RpcMetaData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_RpcMetaData_descriptor,
        new java.lang.String[] { "Trace", });
    internal_static_Trace_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Trace_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_Trace_descriptor,
        new java.lang.String[] { "TraceId", "SpanId", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
