// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: rpcmeta.proto
// Protobuf Java Version: 4.32.0

package com.qifly.core.protocol.frame.meta;

/**
 * <pre>
 * *
 * rpc 元数据定义
 * </pre>
 *
 * Protobuf type {@code RpcMetaData}
 */
@com.google.protobuf.Generated
public final class RpcMetaData extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:RpcMetaData)
    RpcMetaDataOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 32,
      /* patch= */ 0,
      /* suffix= */ "",
      RpcMetaData.class.getName());
  }
  // Use RpcMetaData.newBuilder() to construct.
  private RpcMetaData(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private RpcMetaData() {
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.qifly.core.protocol.frame.meta.RpcMeta.internal_static_RpcMetaData_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.qifly.core.protocol.frame.meta.RpcMeta.internal_static_RpcMetaData_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.qifly.core.protocol.frame.meta.RpcMetaData.class, com.qifly.core.protocol.frame.meta.RpcMetaData.Builder.class);
  }

  private int bitField0_;
  public static final int TRACE_FIELD_NUMBER = 1;
  private com.qifly.core.protocol.frame.meta.Trace trace_;
  /**
   * <code>.Trace trace = 1;</code>
   * @return Whether the trace field is set.
   */
  @java.lang.Override
  public boolean hasTrace() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>.Trace trace = 1;</code>
   * @return The trace.
   */
  @java.lang.Override
  public com.qifly.core.protocol.frame.meta.Trace getTrace() {
    return trace_ == null ? com.qifly.core.protocol.frame.meta.Trace.getDefaultInstance() : trace_;
  }
  /**
   * <code>.Trace trace = 1;</code>
   */
  @java.lang.Override
  public com.qifly.core.protocol.frame.meta.TraceOrBuilder getTraceOrBuilder() {
    return trace_ == null ? com.qifly.core.protocol.frame.meta.Trace.getDefaultInstance() : trace_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(1, getTrace());
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getTrace());
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.qifly.core.protocol.frame.meta.RpcMetaData)) {
      return super.equals(obj);
    }
    com.qifly.core.protocol.frame.meta.RpcMetaData other = (com.qifly.core.protocol.frame.meta.RpcMetaData) obj;

    if (hasTrace() != other.hasTrace()) return false;
    if (hasTrace()) {
      if (!getTrace()
          .equals(other.getTrace())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasTrace()) {
      hash = (37 * hash) + TRACE_FIELD_NUMBER;
      hash = (53 * hash) + getTrace().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.qifly.core.protocol.frame.meta.RpcMetaData parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.qifly.core.protocol.frame.meta.RpcMetaData parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.qifly.core.protocol.frame.meta.RpcMetaData parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.qifly.core.protocol.frame.meta.RpcMetaData parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.qifly.core.protocol.frame.meta.RpcMetaData parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.qifly.core.protocol.frame.meta.RpcMetaData parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.qifly.core.protocol.frame.meta.RpcMetaData parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.qifly.core.protocol.frame.meta.RpcMetaData parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.qifly.core.protocol.frame.meta.RpcMetaData parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.qifly.core.protocol.frame.meta.RpcMetaData parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.qifly.core.protocol.frame.meta.RpcMetaData parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.qifly.core.protocol.frame.meta.RpcMetaData parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.qifly.core.protocol.frame.meta.RpcMetaData prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * *
   * rpc 元数据定义
   * </pre>
   *
   * Protobuf type {@code RpcMetaData}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:RpcMetaData)
      com.qifly.core.protocol.frame.meta.RpcMetaDataOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.qifly.core.protocol.frame.meta.RpcMeta.internal_static_RpcMetaData_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.qifly.core.protocol.frame.meta.RpcMeta.internal_static_RpcMetaData_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.qifly.core.protocol.frame.meta.RpcMetaData.class, com.qifly.core.protocol.frame.meta.RpcMetaData.Builder.class);
    }

    // Construct using com.qifly.core.protocol.frame.meta.RpcMetaData.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage
              .alwaysUseFieldBuilders) {
        internalGetTraceFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      trace_ = null;
      if (traceBuilder_ != null) {
        traceBuilder_.dispose();
        traceBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.qifly.core.protocol.frame.meta.RpcMeta.internal_static_RpcMetaData_descriptor;
    }

    @java.lang.Override
    public com.qifly.core.protocol.frame.meta.RpcMetaData getDefaultInstanceForType() {
      return com.qifly.core.protocol.frame.meta.RpcMetaData.getDefaultInstance();
    }

    @java.lang.Override
    public com.qifly.core.protocol.frame.meta.RpcMetaData build() {
      com.qifly.core.protocol.frame.meta.RpcMetaData result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.qifly.core.protocol.frame.meta.RpcMetaData buildPartial() {
      com.qifly.core.protocol.frame.meta.RpcMetaData result = new com.qifly.core.protocol.frame.meta.RpcMetaData(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.qifly.core.protocol.frame.meta.RpcMetaData result) {
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.trace_ = traceBuilder_ == null
            ? trace_
            : traceBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.qifly.core.protocol.frame.meta.RpcMetaData) {
        return mergeFrom((com.qifly.core.protocol.frame.meta.RpcMetaData)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.qifly.core.protocol.frame.meta.RpcMetaData other) {
      if (other == com.qifly.core.protocol.frame.meta.RpcMetaData.getDefaultInstance()) return this;
      if (other.hasTrace()) {
        mergeTrace(other.getTrace());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              input.readMessage(
                  internalGetTraceFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private com.qifly.core.protocol.frame.meta.Trace trace_;
    private com.google.protobuf.SingleFieldBuilder<
        com.qifly.core.protocol.frame.meta.Trace, com.qifly.core.protocol.frame.meta.Trace.Builder, com.qifly.core.protocol.frame.meta.TraceOrBuilder> traceBuilder_;
    /**
     * <code>.Trace trace = 1;</code>
     * @return Whether the trace field is set.
     */
    public boolean hasTrace() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>.Trace trace = 1;</code>
     * @return The trace.
     */
    public com.qifly.core.protocol.frame.meta.Trace getTrace() {
      if (traceBuilder_ == null) {
        return trace_ == null ? com.qifly.core.protocol.frame.meta.Trace.getDefaultInstance() : trace_;
      } else {
        return traceBuilder_.getMessage();
      }
    }
    /**
     * <code>.Trace trace = 1;</code>
     */
    public Builder setTrace(com.qifly.core.protocol.frame.meta.Trace value) {
      if (traceBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        trace_ = value;
      } else {
        traceBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.Trace trace = 1;</code>
     */
    public Builder setTrace(
        com.qifly.core.protocol.frame.meta.Trace.Builder builderForValue) {
      if (traceBuilder_ == null) {
        trace_ = builderForValue.build();
      } else {
        traceBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.Trace trace = 1;</code>
     */
    public Builder mergeTrace(com.qifly.core.protocol.frame.meta.Trace value) {
      if (traceBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0) &&
          trace_ != null &&
          trace_ != com.qifly.core.protocol.frame.meta.Trace.getDefaultInstance()) {
          getTraceBuilder().mergeFrom(value);
        } else {
          trace_ = value;
        }
      } else {
        traceBuilder_.mergeFrom(value);
      }
      if (trace_ != null) {
        bitField0_ |= 0x00000001;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.Trace trace = 1;</code>
     */
    public Builder clearTrace() {
      bitField0_ = (bitField0_ & ~0x00000001);
      trace_ = null;
      if (traceBuilder_ != null) {
        traceBuilder_.dispose();
        traceBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.Trace trace = 1;</code>
     */
    public com.qifly.core.protocol.frame.meta.Trace.Builder getTraceBuilder() {
      bitField0_ |= 0x00000001;
      onChanged();
      return internalGetTraceFieldBuilder().getBuilder();
    }
    /**
     * <code>.Trace trace = 1;</code>
     */
    public com.qifly.core.protocol.frame.meta.TraceOrBuilder getTraceOrBuilder() {
      if (traceBuilder_ != null) {
        return traceBuilder_.getMessageOrBuilder();
      } else {
        return trace_ == null ?
            com.qifly.core.protocol.frame.meta.Trace.getDefaultInstance() : trace_;
      }
    }
    /**
     * <code>.Trace trace = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.qifly.core.protocol.frame.meta.Trace, com.qifly.core.protocol.frame.meta.Trace.Builder, com.qifly.core.protocol.frame.meta.TraceOrBuilder> 
        internalGetTraceFieldBuilder() {
      if (traceBuilder_ == null) {
        traceBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.qifly.core.protocol.frame.meta.Trace, com.qifly.core.protocol.frame.meta.Trace.Builder, com.qifly.core.protocol.frame.meta.TraceOrBuilder>(
                getTrace(),
                getParentForChildren(),
                isClean());
        trace_ = null;
      }
      return traceBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:RpcMetaData)
  }

  // @@protoc_insertion_point(class_scope:RpcMetaData)
  private static final com.qifly.core.protocol.frame.meta.RpcMetaData DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.qifly.core.protocol.frame.meta.RpcMetaData();
  }

  public static com.qifly.core.protocol.frame.meta.RpcMetaData getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<RpcMetaData>
      PARSER = new com.google.protobuf.AbstractParser<RpcMetaData>() {
    @java.lang.Override
    public RpcMetaData parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<RpcMetaData> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<RpcMetaData> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.qifly.core.protocol.frame.meta.RpcMetaData getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

