// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: rpcmeta.proto
// Protobuf Java Version: 4.32.0

package com.qifly.core.protocol.frame.meta;

@com.google.protobuf.Generated
public interface RpcMetaDataOrBuilder extends
    // @@protoc_insertion_point(interface_extends:RpcMetaData)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.Trace trace = 1;</code>
   * @return Whether the trace field is set.
   */
  boolean hasTrace();
  /**
   * <code>.Trace trace = 1;</code>
   * @return The trace.
   */
  com.qifly.core.protocol.frame.meta.Trace getTrace();
  /**
   * <code>.Trace trace = 1;</code>
   */
  com.qifly.core.protocol.frame.meta.TraceOrBuilder getTraceOrBuilder();
}
