// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: rpcmeta.proto
// Protobuf Java Version: 4.32.0

package com.qifly.core.protocol.frame.meta;

@com.google.protobuf.Generated
public interface TraceOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Trace)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string trace_id = 1;</code>
   * @return The traceId.
   */
  java.lang.String getTraceId();
  /**
   * <code>string trace_id = 1;</code>
   * @return The bytes for traceId.
   */
  com.google.protobuf.ByteString
      getTraceIdBytes();

  /**
   * <code>string span_id = 2;</code>
   * @return The spanId.
   */
  java.lang.String getSpanId();
  /**
   * <code>string span_id = 2;</code>
   * @return The bytes for spanId.
   */
  com.google.protobuf.ByteString
      getSpanIdBytes();
}
