// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: userservice.proto
// Protobuf Java Version: 4.32.0

package com.qiflyyy.userservice.proto;

@com.google.protobuf.Generated
public interface GetUserReqOrBuilder extends
    // @@protoc_insertion_point(interface_extends:GetUserReq)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 id = 1;</code>
   * @return The id.
   */
  long getId();
}
