// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: userservice.proto
// Protobuf Java Version: 4.32.0

package com.qiflyyy.userservice.proto;

@com.google.protobuf.Generated
public interface GetUserResOrBuilder extends
    // @@protoc_insertion_point(interface_extends:GetUserRes)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 1;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();
}
