// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: rpcdata.proto
// Protobuf Java Version: 4.32.0

package com.qifly.core.protocol.data;

/**
 * Protobuf type {@code RpcBody}
 */
@com.google.protobuf.Generated
public final class RpcBody extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:RpcBody)
    RpcBodyOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 32,
      /* patch= */ 0,
      /* suffix= */ "",
      RpcBody.class.getName());
  }
  // Use RpcBody.newBuilder() to construct.
  private RpcBody(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private RpcBody() {
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.qifly.core.protocol.data.RpcData.internal_static_RpcBody_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.qifly.core.protocol.data.RpcData.internal_static_RpcBody_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.qifly.core.protocol.data.RpcBody.class, com.qifly.core.protocol.data.RpcBody.Builder.class);
  }

  private int bitField0_;
  public static final int RPC_ID_FIELD_NUMBER = 1;
  private int rpcId_ = 0;
  /**
   * <code>int32 rpc_id = 1;</code>
   * @return The rpcId.
   */
  @java.lang.Override
  public int getRpcId() {
    return rpcId_;
  }

  public static final int DATA_FIELD_NUMBER = 2;
  private com.google.protobuf.Any data_;
  /**
   * <pre>
   * 请求或响应体
   * </pre>
   *
   * <code>.google.protobuf.Any data = 2;</code>
   * @return Whether the data field is set.
   */
  @java.lang.Override
  public boolean hasData() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <pre>
   * 请求或响应体
   * </pre>
   *
   * <code>.google.protobuf.Any data = 2;</code>
   * @return The data.
   */
  @java.lang.Override
  public com.google.protobuf.Any getData() {
    return data_ == null ? com.google.protobuf.Any.getDefaultInstance() : data_;
  }
  /**
   * <pre>
   * 请求或响应体
   * </pre>
   *
   * <code>.google.protobuf.Any data = 2;</code>
   */
  @java.lang.Override
  public com.google.protobuf.AnyOrBuilder getDataOrBuilder() {
    return data_ == null ? com.google.protobuf.Any.getDefaultInstance() : data_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (rpcId_ != 0) {
      output.writeInt32(1, rpcId_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(2, getData());
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (rpcId_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, rpcId_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getData());
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.qifly.core.protocol.data.RpcBody)) {
      return super.equals(obj);
    }
    com.qifly.core.protocol.data.RpcBody other = (com.qifly.core.protocol.data.RpcBody) obj;

    if (getRpcId()
        != other.getRpcId()) return false;
    if (hasData() != other.hasData()) return false;
    if (hasData()) {
      if (!getData()
          .equals(other.getData())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + RPC_ID_FIELD_NUMBER;
    hash = (53 * hash) + getRpcId();
    if (hasData()) {
      hash = (37 * hash) + DATA_FIELD_NUMBER;
      hash = (53 * hash) + getData().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.qifly.core.protocol.data.RpcBody parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.qifly.core.protocol.data.RpcBody parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.qifly.core.protocol.data.RpcBody parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.qifly.core.protocol.data.RpcBody parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.qifly.core.protocol.data.RpcBody parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.qifly.core.protocol.data.RpcBody parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.qifly.core.protocol.data.RpcBody parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.qifly.core.protocol.data.RpcBody parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.qifly.core.protocol.data.RpcBody parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.qifly.core.protocol.data.RpcBody parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.qifly.core.protocol.data.RpcBody parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.qifly.core.protocol.data.RpcBody parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.qifly.core.protocol.data.RpcBody prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code RpcBody}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:RpcBody)
      com.qifly.core.protocol.data.RpcBodyOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.qifly.core.protocol.data.RpcData.internal_static_RpcBody_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.qifly.core.protocol.data.RpcData.internal_static_RpcBody_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.qifly.core.protocol.data.RpcBody.class, com.qifly.core.protocol.data.RpcBody.Builder.class);
    }

    // Construct using com.qifly.core.protocol.data.RpcBody.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage
              .alwaysUseFieldBuilders) {
        internalGetDataFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      rpcId_ = 0;
      data_ = null;
      if (dataBuilder_ != null) {
        dataBuilder_.dispose();
        dataBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.qifly.core.protocol.data.RpcData.internal_static_RpcBody_descriptor;
    }

    @java.lang.Override
    public com.qifly.core.protocol.data.RpcBody getDefaultInstanceForType() {
      return com.qifly.core.protocol.data.RpcBody.getDefaultInstance();
    }

    @java.lang.Override
    public com.qifly.core.protocol.data.RpcBody build() {
      com.qifly.core.protocol.data.RpcBody result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.qifly.core.protocol.data.RpcBody buildPartial() {
      com.qifly.core.protocol.data.RpcBody result = new com.qifly.core.protocol.data.RpcBody(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.qifly.core.protocol.data.RpcBody result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.rpcId_ = rpcId_;
      }
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.data_ = dataBuilder_ == null
            ? data_
            : dataBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.qifly.core.protocol.data.RpcBody) {
        return mergeFrom((com.qifly.core.protocol.data.RpcBody)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.qifly.core.protocol.data.RpcBody other) {
      if (other == com.qifly.core.protocol.data.RpcBody.getDefaultInstance()) return this;
      if (other.getRpcId() != 0) {
        setRpcId(other.getRpcId());
      }
      if (other.hasData()) {
        mergeData(other.getData());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              rpcId_ = input.readInt32();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 18: {
              input.readMessage(
                  internalGetDataFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private int rpcId_ ;
    /**
     * <code>int32 rpc_id = 1;</code>
     * @return The rpcId.
     */
    @java.lang.Override
    public int getRpcId() {
      return rpcId_;
    }
    /**
     * <code>int32 rpc_id = 1;</code>
     * @param value The rpcId to set.
     * @return This builder for chaining.
     */
    public Builder setRpcId(int value) {

      rpcId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>int32 rpc_id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearRpcId() {
      bitField0_ = (bitField0_ & ~0x00000001);
      rpcId_ = 0;
      onChanged();
      return this;
    }

    private com.google.protobuf.Any data_;
    private com.google.protobuf.SingleFieldBuilder<
        com.google.protobuf.Any, com.google.protobuf.Any.Builder, com.google.protobuf.AnyOrBuilder> dataBuilder_;
    /**
     * <pre>
     * 请求或响应体
     * </pre>
     *
     * <code>.google.protobuf.Any data = 2;</code>
     * @return Whether the data field is set.
     */
    public boolean hasData() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <pre>
     * 请求或响应体
     * </pre>
     *
     * <code>.google.protobuf.Any data = 2;</code>
     * @return The data.
     */
    public com.google.protobuf.Any getData() {
      if (dataBuilder_ == null) {
        return data_ == null ? com.google.protobuf.Any.getDefaultInstance() : data_;
      } else {
        return dataBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * 请求或响应体
     * </pre>
     *
     * <code>.google.protobuf.Any data = 2;</code>
     */
    public Builder setData(com.google.protobuf.Any value) {
      if (dataBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        data_ = value;
      } else {
        dataBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 请求或响应体
     * </pre>
     *
     * <code>.google.protobuf.Any data = 2;</code>
     */
    public Builder setData(
        com.google.protobuf.Any.Builder builderForValue) {
      if (dataBuilder_ == null) {
        data_ = builderForValue.build();
      } else {
        dataBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 请求或响应体
     * </pre>
     *
     * <code>.google.protobuf.Any data = 2;</code>
     */
    public Builder mergeData(com.google.protobuf.Any value) {
      if (dataBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0) &&
          data_ != null &&
          data_ != com.google.protobuf.Any.getDefaultInstance()) {
          getDataBuilder().mergeFrom(value);
        } else {
          data_ = value;
        }
      } else {
        dataBuilder_.mergeFrom(value);
      }
      if (data_ != null) {
        bitField0_ |= 0x00000002;
        onChanged();
      }
      return this;
    }
    /**
     * <pre>
     * 请求或响应体
     * </pre>
     *
     * <code>.google.protobuf.Any data = 2;</code>
     */
    public Builder clearData() {
      bitField0_ = (bitField0_ & ~0x00000002);
      data_ = null;
      if (dataBuilder_ != null) {
        dataBuilder_.dispose();
        dataBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 请求或响应体
     * </pre>
     *
     * <code>.google.protobuf.Any data = 2;</code>
     */
    public com.google.protobuf.Any.Builder getDataBuilder() {
      bitField0_ |= 0x00000002;
      onChanged();
      return internalGetDataFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * 请求或响应体
     * </pre>
     *
     * <code>.google.protobuf.Any data = 2;</code>
     */
    public com.google.protobuf.AnyOrBuilder getDataOrBuilder() {
      if (dataBuilder_ != null) {
        return dataBuilder_.getMessageOrBuilder();
      } else {
        return data_ == null ?
            com.google.protobuf.Any.getDefaultInstance() : data_;
      }
    }
    /**
     * <pre>
     * 请求或响应体
     * </pre>
     *
     * <code>.google.protobuf.Any data = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.google.protobuf.Any, com.google.protobuf.Any.Builder, com.google.protobuf.AnyOrBuilder> 
        internalGetDataFieldBuilder() {
      if (dataBuilder_ == null) {
        dataBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.google.protobuf.Any, com.google.protobuf.Any.Builder, com.google.protobuf.AnyOrBuilder>(
                getData(),
                getParentForChildren(),
                isClean());
        data_ = null;
      }
      return dataBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:RpcBody)
  }

  // @@protoc_insertion_point(class_scope:RpcBody)
  private static final com.qifly.core.protocol.data.RpcBody DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.qifly.core.protocol.data.RpcBody();
  }

  public static com.qifly.core.protocol.data.RpcBody getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<RpcBody>
      PARSER = new com.google.protobuf.AbstractParser<RpcBody>() {
    @java.lang.Override
    public RpcBody parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<RpcBody> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<RpcBody> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.qifly.core.protocol.data.RpcBody getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

