// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: rpcdata.proto
// Protobuf Java Version: 4.32.0

package com.qifly.core.protocol.data;

@com.google.protobuf.Generated
public interface RpcBodyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:RpcBody)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 rpc_id = 1;</code>
   * @return The rpcId.
   */
  int getRpcId();

  /**
   * <pre>
   * 请求或响应体
   * </pre>
   *
   * <code>.google.protobuf.Any data = 2;</code>
   * @return Whether the data field is set.
   */
  boolean hasData();
  /**
   * <pre>
   * 请求或响应体
   * </pre>
   *
   * <code>.google.protobuf.Any data = 2;</code>
   * @return The data.
   */
  com.google.protobuf.Any getData();
  /**
   * <pre>
   * 请求或响应体
   * </pre>
   *
   * <code>.google.protobuf.Any data = 2;</code>
   */
  com.google.protobuf.AnyOrBuilder getDataOrBuilder();
}
